### PR TITLE
Faster closest commonsuperview

### PR DESCRIPTION
**Pull request by Reflejo**
The general idea is to move from an O(n^2) algorithm to a O(N) where N is the height of the view hierarchy tree. The algorithm is very simple: traverse the tree up starting from both views and keep the visited views in a set. When any of the nodes was already visited before: that must be the common superview.

More info: #51

### CODE REVIEW

**Comment by robertjpayne** [comment]
Hey @Reflejo believe this contains a typo in the do while loop looks like two `fromView = view.superview`?

Reckon there is much downside to using NSSet vs Set? We could then put this into develop?

**Comment by Reflejo** [comment]
@robertjpayne Ok, I just changed `Set<>` to `NSMutableSet`. But I don't see any typo.

By the way, Is there any reason you want to support Swift 1.0+ ?. I think that moving forward, it'd be very beneficial to incorporate all the changes of a fast evolving language like Swift.

**Comment by Reflejo** [comment]
Closing this. I'm gonna create a new one against `develop`

**Comment by robertjpayne** [comment]
@Reflejo there was a typo in the commit I looked at but you had fixed it in a subsequent one my mistake.

I want to maintain Swift 1.0 support until Swift 1.2 is out unless we have really good reason not to. Mostly just so we don't have to maintain two branches separately. I'm all for ditching NSSet and sorts as soon as Swift 1.2 is released but it's quite likely not going to be a public release until May or later.

**Pull request closed without merging**
