### PR TITLE
Fixed constraints leak + performance optimizations

### PR DESCRIPTION
**Pull request by Reflejo**
This is probably the most urgent one.

### CODE REVIEW

**Comment by robertjpayne** [comment]
These updates should be in develop now, I sort of manually merged because I'm working on some other things and am shifting some stuff around.

**Comment by Reflejo** [comment]
Nice. :100:

**Comment by robertjpayne** [comment]
Also I flagged everything as final as from my understanding it can improve performance.

**Comment by robertjpayne** [comment]
@Reflejo actually just fixed another bug that was still causing the constraints to be around forever <eek>.

The leak you found I think wasn't too major ( mostly only bad for views that live forever ). As soon as all views involved with a constraint bunch ( basically UIViewController and down ) it would definitely clean up.

All fixed now either way on develop!

**Pull request closed without merging**
